# Generated by Django 4.0.1 on 2022-03-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ingredient_account_first_name_account_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='app.Recipe'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
