# Generated by Django 4.0.1 on 2022-04-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_account_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
