# Generated by Django 4.0.1 on 2022-04-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_account_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_glutenFree',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_vegan',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
