# Generated by Django 4.0.1 on 2022-04-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_recipe_calories_recipe_is_glutenfree_recipe_is_vegan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipeImg'),
        ),
    ]
